### ISSUE TITLE
FSharp.Core  4.3.0.0 Not Found With VS 2015 Update 3

### ISSUE THREAD

**Issue by ghost** [markusl/GoogleTestRunner#21]
I have installed VS 2015 Community Edition Update 3, google test, and GoogleTest Runner.

I can run my tests by executing my tests project. The tests are discovered by GoogleTest Runner, but when I attempt to run the tests using GoogleTest Runner, I get the following error:

Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at FSharp.Data.Runtime.XmlRuntime.GetChildrenArray(XmlElement value, String nameWithNS)
   at FSharp.Data.Runtime.XmlRuntime.ConvertArray[R](XmlElement xml, String nameWithNS, Func`2 f)
   at GoogleTestRunner.ResultParser.getResults(IMessageLogger logger, String outputPath, FSharpList`1 testCases)
   at GoogleTestRunner.GoogleTestExecutor.runOnce(IFrameworkHandle framework, IRunContext runContext, FSharpList`1 allCases, FSharpList`1 cases, String executable, Boolean runAll)
   at GoogleTestRunner.GoogleTestExecutor.runTests(FSharpList`1 allCases, IEnumerable`1 cases, IRunContext runContext, IFrameworkHandle framework, Boolean runAll)

**Comment by ericsebesta** [comment]
I'm seeing the same. I forked and poked around, but my knowledge of VSIX is pretty weak, as is my .Net and F# knowledge :/

**Comment by visuve** [comment]
https://github.com/markusl/GoogleTestRunner/issues/20

**Comment by ramitrathore** [comment]
I have a same issue.. is there any workaround?

**Comment by jagd** [comment]
Hi @ramitrathore , I think you could just ignore that message.
Finally I found out it more or less works regardless this message.
